site_name: Research Notebook
site_author: Gregory E. Maurer
#pages:
#    - Home: 'index.md'
#    - Activity Log: 'activitylog.md'
#    - To Do list: 'todo.md'
#    - Sites: 'sites/SitesIndex.md'
theme:
  name: material
  palette:
    scheme: slate
    primary: lime
repo_url: https://github.com/gremau/research-notebook
site_url: https://greg.pronghorns.net/research-notebook
edit_uri: edit/main/docs/
